#!/bin/bash
参考链接：https://gist.github.com/crazycode/53bd7a5b8ea8bad7ec56


#安装依赖：
yum install -y make gcc binutils gcc-c++ compat-libstdc++ elfutils-libelf-devel elfutils-libelf-devel-static \
ksh libaio libaio-devel numactl-devel sysstat unixODBC unixODBC-devel pcre-devel glibc.i686 compat-libstdc++-33

#用户和组准备
groupadd oinstall
groupadd dba
useradd -g oinstall -G dba -d /home/oracle oracle
echo "passwordXX" | passwd oracle --stdin

#.....
解压数据库安装包的database文件夹到/home/oracle/database！

#目录准备及权限调整
mkdir -p /export/servers/oracle/11.2.0  		#数据库系统安装目录
mkdir -p /export/data/oradata    			#数据库数据安装目录
mkdir -p /export/data/oradata_back  			#数据备份目录
mkdir -p /home/oracle/inventory 			#清单目录
chown -R oracle:oinstall /export/servers/oracle
chown -R oracle:oinstall /home/oracle/inventory
chown -R oracle:oinstall /export/data
chmod -R 775 /export/servers/oracle
chmod -R 775 /export/data

#内核参数调整
echo >> /etc/sysctl.conf <<-eof
fs.aio-max-nr = 1048576
fs.file-max = 6553600
kernel.shmall = 2097152
kernel.shmmax = 2147483648
kernel.shmmni = 4096
kernel.sem = 250 32000 100 128
net.ipv4.ip_local_port_range = 1024 65000
net.core.rmem_default = 262144
net.core.rmem_max = 4194304
net.core.wmem_default = 262144
net.core.wmem_max = 1048586
eof

/sbin/sysctl -p
			
#用户资源限制修改
echo >> /etc/security/limits.conf <<-eof
oracle           soft    nproc           2047
oracle           hard    nproc           16384
oracle           soft    nofile          1024
oracle           hard    nofile          65536
oracle           soft    stack           10240
eof

#认证模块
echo >> /etc/pam.d/login  <<eof
session  required   /lib64/security/pam_limits.so
session  required   pam_limits.so
eof

echo >> /etc/profile  <<eof
if [ $USER = "oracle" ]; then
 if [ $SHELL = "/bin/ksh" ]; then
  ulimit -p 16384
  ulimit -n 65536
 else
  ulimit -u 16384 -n 65536
 fi
fi
eof

#开始安装：
#打开另一个终端并用oracle用户登录!(不要su过去，直接用oracle登陆)
#复制并修改应答文件
cp -R /home/oracle/database/response/db_install.rsp  /home/oracle/database/response/my_db_install.rsp	#备份模板文件以便回滚

#按实际情况修改以下项（测试时全部使用的如下默认配置）
vim /home/oracle/database/response/my_db_install.rsp	
oracle.install.option=INSTALL_DB_SWONLY
ORACLE_HOSTNAME=localhost
UNIX_GROUP_NAME=oinstall
INVENTORY_LOCATION=/home/oracle/inventory/
ORACLE_HOME=/export/servers/oracle/11.2.0
ORACLE_BASE=/export/servers/oracle
oracle.install.db.InstallEdition=EE
oracle.install.db.isCustomInstall=false
oracle.install.db.DBA_GROUP=dba
oracle.install.db.OPER_GROUP=dba
DECLINE_SECURITY_UPDATES=true


#切换到oracle身份，若已经是此用户可跳过
sudo su - oracle
cd /home/oracle/database/  ;  ./runInstaller -silent -responseFile /home/oracle/database/response/my_db_install.rsp

#注：如果安装过程中报错则在root登陆的终端执行如下命令删除inventory.xml文件后再重新执行上面的命令：
rm -rf /home/oracle/inventory/ContentsXML/inventory.xml

#等待提示切换到root用户的终端，根据提示执行类似如下的2个脚本（不要直接拷贝！根据命令行提示执行！）
/home/oracle/inventory/orainstRoot.sh
/export/servers/oracle/11.2.0/root.sh

#切换到oracle用户的终端，敲"回车"，完成安装

#修改oracle用户环境变量（在oracle用户所在的那个终端执行！）
vim ~/.bash_profile
export ORACLE_SID=orcl
export ORACLE_BASE=/export/servers/oracle
export ORACLE_HOME=$ORACLE_BASE/product/11.2.0/db_1
export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib
export PATH=$PATH:$ORACLE_HOME/bin

#刷新环变：
source ~/.bash_profile

#补充！（使用root身份）正常来说，上面定义的环境变量的文件路径应该是已经存在的，但是没有，所以使用下面命令手动创建了...
mkdir -p -m 755 /export/servers/oracle/product/11.2.0/db_1/lib
mkdir -p -m 755 /export/servers/oracle/product/11.2.0/db_1/network/admin


#安装后工作：
#建库：
#复制并编辑应答文件：
cp -R /home/oracle/database/response/dbca.rsp  /home/oracle/database/response/my_dbca.rsp
vim /home/oracle/database/response/my_dbca.rsp
OPERATION_TYPE = "createDatabase"
GDBNAME = "orcl11g"
SID = "orcl"				#SID (实例?)
SYSPASSWORD = "passwordXX"
SYSTEMPASSWORD = "passwordXX"
DATAFILEDESTINATION = /export/data/oradata
RECOVERYAREADESTINATION = /export/data/oradata_back
SYSDBAUSERNAME = "system"		#管理账号：system
SYSDBAPASSWORD = "passwordXX"		#管理密码：passwordXX
#以上2项可选
INSTANCENAME = "实例名"
CHARACTERSET = "UTF8" 			#按需求设置，建议使用UTF8
NATIONALCHARACTERSET= "UTF8" 		#可选 "UTF8" or "AL16UTF16" 建议UTF8
TOTALMEMORY = "1024" 			#使用最大内存，单位M建库（根据实际内存容量来规划）


#创建目录：
mkdir -p -m 755 /export/data/oradata/orcl11g

#关闭防火墙：（root身份的终端执行）要写入开机自启！
setenforce 0
service iptables stop

echo "setenforce 0" >> /etc/rc.local
echo "service iptables stop" >> /etc/rc.local


mkdir -p /export/servers/oracle/cfgtoollogs/dbca
mkdir -p /export/servers/oracle/cfgtoollogs/dbca/orcl11g
chmod 777 -R /export/servers/

#静默建库：(如果提示没有找到下面dbca的路径则使用find名查找它的位置：find / -iname "dbca" ,注：要使用oracle用户执行！)
/export/servers/oracle/11.2.0/bin/dbca -silent -responseFile /home/oracle/database/response/my_dbca.rsp


#配置监听：(如果提示没有找到下面netca的路径则使用find名查找它的位置：find / -iname "netca" ,注：要用oracle用户执行！)
/export/servers/oracle/11.2.0/bin/netca /silent /responsefile /home/oracle/database/response/netca.rsp 

#执行完成会在 $ORACLE_HOME/network/admin目录下生成sqlnet.ora和listener.ora两个文件。

#注册sid(有问题，但不影响启动，这个文件不存在..)
mkdir -p  /export/servers/oracle/product/11.2.0/db_1/network/admin/
vim $ORACLE_HOME/network/admin/listener.ora	#在文件最后添加如下：

SID_LIST_LISTENER =
(SID_LIST =
    (SID_DESC =
    (SID_NAME = orcl)
    (ORACLE_HOME = /app/servers/oracle/product/11.2.0/db_1)
    (PROGRAM = extproc)
    )
)

LISTENER =
(DESCRIPTION_LIST =
(DESCRIPTION =
    (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
)
)

--------------------------------------------------------------------------

#启动服务：（除了修改/etc/oratab这一步外，下面的操作都要使用oracle身份执行！）
vim 修改：/etc/oratab
将：orcl:/export/servers/oracle/11.2.0:N
改为：orcl:/export/servers/oracle/11.2.0:Y
#注：开头的orcl为实例名（参考：http://jingyan.baidu.com/article/b2c186c8fe4306c46ef6ff16.html）

nohup /export/servers/oracle/11.2.0/bin/tnslsnr &
/export/servers/oracle/11.2.0/bin/dbstart #（会提示：ORACLE_HOME_LISTNER 没设置）


#开启自启：（使用root身份执行！）
cat >> /etc/rc.local <<-eof
su oracle -lc "nohup /export/servers/oracle/11.2.0/bin/tnslsnr &"
su oracle -lc "/export/servers/oracle/11.2.0/bin/dbstart"
eof
 
